from datetime import datetime, timezone
from sqlalchemy.orm import Session
from app.models import Incident
from app.hindsight_service import hindsight_service

SEED_INCIDENTS = [
    # --- 1. Database Failures ---
    {
        "id": "INC-101",
        "service": "Payment API",
        "error": "Database connection timeout",
        "symptoms": "High HTTP 504 Gateway Timeouts on /v1/charge endpoint, elevated API latency",
        "severity": "high",
        "root_cause": "Connection pool exhaustion due to leaked unclosed DB sessions during traffic surge",
        "resolution": "Increased connection pool size from 20 to 100 and deployed hotfix for session leak",
        "post_mortem": "Connection pool configuration was insufficient for observed traffic surges. Added automated connection pool utilization alerting at 80% capacity.",
        "outcome": "Resolved",
        "created_at": datetime(2026, 3, 15, 10, 30, 0, tzinfo=timezone.utc),
        "resolved_at": datetime(2026, 3, 15, 11, 15, 0, tzinfo=timezone.utc),
    },
    {
        "id": "INC-102",
        "service": "Customer Relational Database",
        "error": "Database connection problems & client pool refusal",
        "symptoms": "FATAL: remaining connection slots are reserved for non-replication superuser connections",
        "severity": "critical",
        "root_cause": "Zombie ORM worker connections staying open after unexpected microservice crashes",
        "resolution": "Configured idle connection timeout setting in PgBouncer and restarted orphaned backend instances",
        "post_mortem": "Worker processes failed to clean up idle connection pools upon crashes. Added PgBouncer connection limits and process crash recovery hooks.",
        "outcome": "Resolved",
        "created_at": datetime(2026, 3, 16, 9, 15, 0, tzinfo=timezone.utc),
        "resolved_at": datetime(2026, 3, 16, 10, 0, 0, tzinfo=timezone.utc),
    },
    {
        "id": "INC-103",
        "service": "User API",
        "error": "Database deadlocks on user profile update",
        "symptoms": "HTTP 500 Internal Server Error spike during user batch update requests",
        "severity": "high",
        "root_cause": "Unordered SQL updates across user_profiles table causing circular lock waits",
        "resolution": "Enforced strict alphabetical lock ordering in ORM transaction handler",
        "post_mortem": "ORM batch update queries lacked lock ordering rules. Added CI database lint check for batch queries.",
        "outcome": "Resolved",
        "created_at": datetime(2026, 3, 17, 11, 20, 0, tzinfo=timezone.utc),
        "resolved_at": datetime(2026, 3, 17, 12, 0, 0, tzinfo=timezone.utc),
    },
    {
        "id": "INC-104",
        "service": "Analytics Data Store",
        "error": "MongoDB primary node stepdown & election loop",
        "symptoms": "Write operations failing with AutoReconnect error across secondary analytics pipeline",
        "severity": "critical",
        "root_cause": "Network partition between primary data center and MongoDB arbiter node during switch maintenance",
        "resolution": "Reconfigured MongoDB replica set priorities and stabilized network routing",
        "post_mortem": "Arbiter node placement on single network rack caused split-brain election loops during network maintenance.",
        "outcome": "Resolved",
        "created_at": datetime(2026, 3, 18, 14, 0, 0, tzinfo=timezone.utc),
        "resolved_at": datetime(2026, 3, 18, 14, 45, 0, tzinfo=timezone.utc),
    },

    # --- 2. API Failures ---
    {
        "id": "INC-105",
        "service": "Checkout Gateway",
        "error": "API latency and response degradation",
        "symptoms": "P99 response time jumped from 120ms to 4800ms; downstream payment webhooks timing out",
        "severity": "high",
        "root_cause": "Unindexed full-table scan on transaction_logs during high-volume query execution",
        "resolution": "Created composite index on (created_at, account_id) and enabled query caching in Redis",
        "post_mortem": "Unindexed query on transaction_logs caused full table scans. Enforced index requirement checks in CI/CD migration pipeline.",
        "outcome": "Resolved",
        "created_at": datetime(2026, 3, 19, 11, 0, 0, tzinfo=timezone.utc),
        "resolved_at": datetime(2026, 3, 19, 12, 10, 0, tzinfo=timezone.utc),
    },
    {
        "id": "INC-106",
        "service": "GraphQL API Gateway",
        "error": "GraphQL query depth limit exhaustion",
        "symptoms": "High CPU utilization on gateway pods; API clients receiving 504 gateway timeout",
        "severity": "medium",
        "root_cause": "Deeply nested circular GraphQL queries submitted by third-party partner integration",
        "resolution": "Configured GraphQL query depth complexity limiting (max depth 6) and query cost analysis middleware",
        "post_mortem": "GraphQL gateway lacked query depth limits. Added cost analysis and rate limits per API client key.",
        "outcome": "Resolved",
        "created_at": datetime(2026, 3, 20, 15, 30, 0, tzinfo=timezone.utc),
        "resolved_at": datetime(2026, 3, 20, 16, 15, 0, tzinfo=timezone.utc),
    },
    {
        "id": "INC-107",
        "service": "Partner Integration Gateway",
        "error": "API Rate limit threshold misconfiguration",
        "symptoms": "Valid customer requests receiving HTTP 429 Too Many Requests errors",
        "severity": "medium",
        "root_cause": "Rate limit bucket reset interval configured in seconds instead of milliseconds in Kong API gateway",
        "resolution": "Updated Kong rate limiting plugin config to 1000ms window and reloaded ingress configuration",
        "post_mortem": "Unit conversion mistake during gateway deployment throttled requests 1000x stricter than intended.",
        "outcome": "Resolved",
        "created_at": datetime(2026, 3, 21, 8, 45, 0, tzinfo=timezone.utc),
        "resolved_at": datetime(2026, 3, 21, 9, 15, 0, tzinfo=timezone.utc),
    },

    # --- 3. Authentication & Security Issues ---
    {
        "id": "INC-108",
        "service": "Auth Service",
        "error": "Authentication service failure & token refresh errors",
        "symptoms": "Users unexpectedly logged out; HTTP 401 Unauthorized spike across login endpoints",
        "severity": "critical",
        "root_cause": "Clock skew across auth cluster instances after NTP service restart causing invalid token signatures",
        "resolution": "Resynchronized NTP daemon across all nodes and rotated auth signing keys",
        "post_mortem": "NTP service daemon configuration lacked drift limits across nodes. Added chrony status monitoring to cluster health checks.",
        "outcome": "Resolved",
        "created_at": datetime(2026, 3, 22, 14, 0, 0, tzinfo=timezone.utc),
        "resolved_at": datetime(2026, 3, 22, 14, 45, 0, tzinfo=timezone.utc),
    },
    {
        "id": "INC-109",
        "service": "HashiCorp Vault Service",
        "error": "Vault Dynamic Secret Lease Expiration causing Auth Crashes",
        "symptoms": "PostgreSQL database login errors: role 'v-token-xyz' does not exist",
        "severity": "critical",
        "root_cause": "Vault renewal sidecar container failed due to expired Vault token permission policy",
        "resolution": "Renewed root Vault token, updated sidecar policy TTL to 24 hours, and restarted auth pods",
        "post_mortem": "Sidecar container Vault renewal token expired without retry alert. Updated Vault token renewal policy TTL to 24 hours and added health probes.",
        "outcome": "Resolved",
        "created_at": datetime(2026, 3, 23, 10, 0, 0, tzinfo=timezone.utc),
        "resolved_at": datetime(2026, 3, 23, 10, 45, 0, tzinfo=timezone.utc),
    },
    {
        "id": "INC-110",
        "service": "OAuth2 SSO Gateway",
        "error": "State parameter validation mismatch",
        "symptoms": "Users receiving Invalid State Parameter error during enterprise Single Sign-On (SSO)",
        "severity": "high",
        "root_cause": "Distributed session cache key expiration set too short (30 seconds) during multi-region failover",
        "resolution": "Increased OAuth2 state token TTL to 5 minutes and aligned Redis session replication across regions",
        "post_mortem": "Short state token TTL caused false positive security validation failures during cross-region authentication.",
        "outcome": "Resolved",
        "created_at": datetime(2026, 3, 24, 13, 20, 0, tzinfo=timezone.utc),
        "resolved_at": datetime(2026, 3, 24, 14, 0, 0, tzinfo=timezone.utc),
    },

    # --- 4. Network & Service Mesh Outages ---
    {
        "id": "INC-111",
        "service": "CoreDNS Resolver Cluster",
        "error": "Cluster internal DNS resolution timeout",
        "symptoms": "i/o timeout errors resolving *.cluster.local service names across all microservice namespaces",
        "severity": "high",
        "root_cause": "UDP packet loss in CoreDNS pods due to socket buffer exhaustion during DNS query spike",
        "resolution": "Autoscaled CoreDNS deployment to 10 replicas and enabled autopath plugin for search domain optimization",
        "post_mortem": "CoreDNS query spikes led to UDP socket buffer packet drops. Configured HPA for CoreDNS deployment and autopath DNS optimization.",
        "outcome": "Resolved",
        "created_at": datetime(2026, 3, 25, 11, 20, 0, tzinfo=timezone.utc),
        "resolved_at": datetime(2026, 3, 25, 12, 0, 0, tzinfo=timezone.utc),
    },
    {
        "id": "INC-112",
        "service": "Service Mesh Proxy",
        "error": "TLS Certificate Expiration on Internal gRPC Endpoints",
        "symptoms": "transport: authentication handshake failed: x509: certificate expired",
        "severity": "critical",
        "root_cause": "Cert-manager webhook renewal pipeline stalled due to failed Let's Encrypt ACME challenge retry",
        "resolution": "Manually re-issued cert-manager ClusterIssuer resource and triggered secret rotation across Istio proxies",
        "post_mortem": "Cert-manager webhook renewal failed silently. Added expiration monitoring alerts for internal gRPC TLS certificates 7 days in advance.",
        "outcome": "Resolved",
        "created_at": datetime(2026, 3, 26, 16, 0, 0, tzinfo=timezone.utc),
        "resolved_at": datetime(2026, 3, 26, 16, 30, 0, tzinfo=timezone.utc),
    },
    {
        "id": "INC-113",
        "service": "VPC Peering Gateway",
        "error": "Cross-VPC network route drop",
        "symptoms": "Microservices in us-east-1 unable to communicate with database cluster in us-east-2",
        "severity": "high",
        "root_cause": "Accidental deletion of VPC peering route table entry during Terraform infrastructure apply",
        "resolution": "Re-applied Terraform VPC module state and verified cross-region route table entries",
        "post_mortem": "Terraform state drift caused destructive route table update. Added explicit preventive lifecycle rules in Terraform manifests.",
        "outcome": "Resolved",
        "created_at": datetime(2026, 3, 27, 9, 10, 0, tzinfo=timezone.utc),
        "resolved_at": datetime(2026, 3, 27, 9, 50, 0, tzinfo=timezone.utc),
    },

    # --- 5. Memory & Resource Exhaustion ---
    {
        "id": "INC-114",
        "service": "Notification Worker",
        "error": "Notification service failure due to Redis queue OOM",
        "symptoms": "Background push notifications and SMS alerts failing to send, queue backlog exceeding 50,000 tasks",
        "severity": "medium",
        "root_cause": "Expired notification payload keys missing TTL config causing memory exhaustion in Redis buffer",
        "resolution": "Applied volatile-lru eviction policy and backfilled TTLs for queued tasks",
        "post_mortem": "Expired Redis keys lacked TTL eviction policy. Updated Redis queue configuration to volatile-lru and enforced key TTL checks.",
        "outcome": "Resolved",
        "created_at": datetime(2026, 3, 28, 8, 10, 0, tzinfo=timezone.utc),
        "resolved_at": datetime(2026, 3, 28, 9, 30, 0, tzinfo=timezone.utc),
    },
    {
        "id": "INC-115",
        "service": "Kubernetes Ingress Gateway",
        "error": "HTTP 502 Bad Gateway across API endpoints",
        "symptoms": "Spike in 502 error rates on ingress controller; upstream pods failing readiness probes",
        "severity": "high",
        "root_cause": "Uncapped pod memory limits resulting in Linux OOMKilled crashes during batch request processing",
        "resolution": "Increased container memory request/limit ratio and enabled Horizontal Pod Autoscaler (HPA)",
        "post_mortem": "Inadequate container memory limits caused unexpected OOM Kills. Implemented resource request/limit standard guidelines in Kubernetes manifests.",
        "outcome": "Resolved",
        "created_at": datetime(2026, 3, 29, 14, 20, 0, tzinfo=timezone.utc),
        "resolved_at": datetime(2026, 3, 29, 15, 0, 0, tzinfo=timezone.utc),
    },
    {
        "id": "INC-116",
        "service": "Report Generator Worker",
        "error": "Node.js Heap Out of Memory",
        "symptoms": "FATAL ERROR: Reached heap limit Allocation failed - JavaScript heap out of memory",
        "severity": "medium",
        "root_cause": "PDF report generation service loaded entire 500k row CSV into V8 memory buffer instead of streaming chunks",
        "resolution": "Refactored PDF generator service to stream CSV rows via Node.js Transform streams and set max-old-space-size=4096",
        "post_mortem": "In-memory file buffering scales quadratically with dataset size. Enforced stream processing patterns for all file generator workers.",
        "outcome": "Resolved",
        "created_at": datetime(2026, 3, 30, 10, 15, 0, tzinfo=timezone.utc),
        "resolved_at": datetime(2026, 3, 30, 11, 30, 0, tzinfo=timezone.utc),
    },
    {
        "id": "INC-117",
        "service": "Image Processing Engine",
        "error": "Python GIL CPU Saturation",
        "symptoms": "CPU utilization stuck at 100% on worker nodes; image thumbnail creation latency spiking to >30s",
        "severity": "medium",
        "root_cause": "Synchronous CPU-bound PIL image resizing running in single-threaded EventLoop blocking async tasks",
        "resolution": "Offloaded image processing tasks to ProcessPoolExecutor multiprocessing worker pool",
        "post_mortem": "CPU-bound tasks in Python blocked single-thread event loops. Isolated heavy image processing into dedicated Celery workers.",
        "outcome": "Resolved",
        "created_at": datetime(2026, 3, 31, 16, 0, 0, tzinfo=timezone.utc),
        "resolved_at": datetime(2026, 3, 31, 17, 10, 0, tzinfo=timezone.utc),
    },

    # --- 6. Event Streaming & Messaging ---
    {
        "id": "INC-118",
        "service": "Event Streaming Pipeline",
        "error": "Kafka Consumer Group Rebalance Storm",
        "symptoms": "Consumer lag spiking to >100k messages; stream processing latency exceeded 10 minutes",
        "severity": "critical",
        "root_cause": "Max poll interval timeout exceeded by heavy synchronous database batch processing in stream loop",
        "resolution": "Offloaded DB writes to asynchronous worker pools and adjusted max.poll.interval.ms to 600,000ms",
        "post_mortem": "Synchronous DB writes blocked Kafka consumer message polling loop. Migrated stream event handlers to async worker queues.",
        "outcome": "Resolved",
        "created_at": datetime(2026, 4, 1, 8, 45, 0, tzinfo=timezone.utc),
        "resolved_at": datetime(2026, 4, 1, 9, 40, 0, tzinfo=timezone.utc),
    },
    {
        "id": "INC-119",
        "service": "RabbitMQ Task Broker",
        "error": "RabbitMQ memory alarm triggered & publisher channel blockage",
        "symptoms": "Publishers receiving channel block warnings; high memory alarm threshold reached (4GB limit)",
        "severity": "high",
        "root_cause": "Dead letter exchange queue filled up without consumer handling expired payload retries",
        "resolution": "Purged dead-letter queue backlog, set x-max-length policy, and increased cluster memory high watermark",
        "post_mortem": "RabbitMQ dead-letter exchange backlog accumulated unhandled expired messages. Implemented queue length alarms and auto-purging dead letter policy.",
        "outcome": "Resolved",
        "created_at": datetime(2026, 4, 2, 9, 30, 0, tzinfo=timezone.utc),
        "resolved_at": datetime(2026, 4, 2, 10, 15, 0, tzinfo=timezone.utc),
    },

    # --- 7. Storage & Search Systems ---
    {
        "id": "INC-120",
        "service": "Search Indexer",
        "error": "Elasticsearch cluster yellow state",
        "symptoms": "Search results lagging behind database updates by >15 minutes",
        "severity": "low",
        "root_cause": "Unassigned replica shards due to insufficient disk space on data node 2",
        "resolution": "Expanded volume capacity and triggered shard allocation rebalance",
        "post_mortem": "Data node storage allocation threshold was unmonitored. Added auto-expanding EBS volumes and disk space alarms at 85%.",
        "outcome": "Resolved",
        "created_at": datetime(2026, 4, 3, 16, 0, 0, tzinfo=timezone.utc),
        "resolved_at": datetime(2026, 4, 3, 17, 20, 0, tzinfo=timezone.utc),
    },
    {
        "id": "INC-121",
        "service": "Central Logging Aggregator",
        "error": "Logstash ingestion pipeline backpressure stalling Filebeat",
        "symptoms": "Log latency in Kibana >2 hours behind real time; Kubernetes nodes dropping log buffers",
        "severity": "medium",
        "root_cause": "Elasticsearch cluster reached flood_stage disk watermark (95% usage), blocking index writes",
        "resolution": "Applied ILM policy to delete index snapshots older than 30 days and reset index.blocks.read_only_allow_delete",
        "post_mortem": "Elasticsearch disk usage reached read-only flood stage threshold. Automated snapshot ILM cleanup policy for indices older than 30 days.",
        "outcome": "Resolved",
        "created_at": datetime(2026, 4, 4, 15, 10, 0, tzinfo=timezone.utc),
        "resolved_at": datetime(2026, 4, 4, 16, 0, 0, tzinfo=timezone.utc),
    },
    {
        "id": "INC-122",
        "service": "Media Storage Service",
        "error": "AWS S3 AccessDenied Exception during file upload",
        "symptoms": "HTTP 403 Forbidden on avatar and attachment uploads across web and mobile clients",
        "severity": "medium",
        "root_cause": "Stale IAM role session policy attached to EKS service account missing s3:PutObjectAcl permission",
        "resolution": "Updated IAM policy JSON with s3:PutObjectAcl and recycled EKS worker service account pods",
        "post_mortem": "Service account IAM policy lacked explicit PutObjectAcl action. Added automated IAM policy linting in Terraform pipeline.",
        "outcome": "Resolved",
        "created_at": datetime(2026, 4, 5, 12, 10, 0, tzinfo=timezone.utc),
        "resolved_at": datetime(2026, 4, 5, 12, 50, 0, tzinfo=timezone.utc),
    },

    # --- 8. CDN & Edge Routing ---
    {
        "id": "INC-123",
        "service": "Cloudflare CDN Edge",
        "error": "CDN Edge Cache Stale Data & Cache Invalidation Failure",
        "symptoms": "Users seeing outdated UI web assets and stale API response payloads after blue/green deployment",
        "severity": "low",
        "root_cause": "Cache-Control header configured with s-maxage=86400 without Cache-Tag header for targeted purge",
        "resolution": "Triggered full CDN cache purge and updated Cache-Control header to no-cache, must-revalidate for dynamic routes",
        "post_mortem": "CDN Cache-Control headers lacked Cache-Tag tags for targeted invalidation. Configured revalidation headers for dynamic asset routes.",
        "outcome": "Resolved",
        "created_at": datetime(2026, 4, 6, 14, 0, 0, tzinfo=timezone.utc),
        "resolved_at": datetime(2026, 4, 6, 14, 25, 0, tzinfo=timezone.utc),
    },
    {
        "id": "INC-124",
        "service": "Nginx Ingress Router",
        "error": "Nginx upstream buffer overflow",
        "symptoms": "HTTP 502 Bad Gateway with 'upstream sent too big header while reading response header from upstream'",
        "severity": "medium",
        "root_cause": "JWT authentication token size grew beyond 4KB default proxy buffer size due to expanded permission scopes",
        "resolution": "Increased proxy_buffer_size and proxy_buffers parameters to 16k in Nginx ingress ConfigMap",
        "post_mortem": "Expanded OAuth user claim permissions increased header sizes. Added proxy buffer size tuning standard to all ingress configurations.",
        "outcome": "Resolved",
        "created_at": datetime(2026, 4, 7, 11, 30, 0, tzinfo=timezone.utc),
        "resolved_at": datetime(2026, 4, 7, 12, 10, 0, tzinfo=timezone.utc),
    },

    # --- 9. Monitoring & Observability ---
    {
        "id": "INC-125",
        "service": "Prometheus Monitoring Service",
        "error": "Prometheus TSDB Write Ahead Log (WAL) Corruption",
        "symptoms": "Prometheus server pod stuck in CrashLoopBackOff with 'err=corrupted WAL segment'",
        "severity": "high",
        "root_cause": "Hard node shutdown during cloud provider maintenance without clean SIGTERM shutdown",
        "resolution": "Removed corrupted WAL segment files from TSDB storage directory and restarted Prometheus instance",
        "post_mortem": "Unclean host node shutdown corrupted TSDB WAL segment. Configured graceful termination grace period on monitoring pods.",
        "outcome": "Resolved",
        "created_at": datetime(2026, 4, 8, 7, 50, 0, tzinfo=timezone.utc),
        "resolved_at": datetime(2026, 4, 8, 8, 30, 0, tzinfo=timezone.utc),
    },
    {
        "id": "INC-126",
        "service": "Datadog Agent Forwarder",
        "error": "APM Trace Drop & Buffer Overflow",
        "symptoms": "Distributed traces missing in Datadog APM dashboard for checkout and auth services",
        "severity": "low",
        "root_cause": "Agent max_traces_per_second limit exceeded during black friday marketing campaign traffic spike",
        "resolution": "Increased APM trace sampling buffer limits and configured adaptive trace sampling in agent YAML",
        "post_mortem": "Static trace sampling limits dropped traces during traffic spikes. Implemented adaptive sampling rates.",
        "outcome": "Resolved",
        "created_at": datetime(2026, 4, 9, 13, 0, 0, tzinfo=timezone.utc),
        "resolved_at": datetime(2026, 4, 9, 13, 40, 0, tzinfo=timezone.utc),
    },

    # --- 10. Deployment & CI/CD Incidents ---
    {
        "id": "INC-127",
        "service": "Kubernetes Deployment Controller",
        "error": "ErrImagePull / ImagePullBackOff on Production Release",
        "symptoms": "Pods failing to start after deployment pipeline execution; cluster deployment stuck at 0/10 ready",
        "severity": "high",
        "root_cause": "Docker image tag typo in GitOps manifest pointing to non-existent release tag v2.4.11-rc1",
        "resolution": "Corrected image tag in Helm values file to v2.4.11 and forced deployment sync",
        "post_mortem": "Image tag was manually edited in release PR instead of automated semantic release tag generation.",
        "outcome": "Resolved",
        "created_at": datetime(2026, 4, 10, 15, 0, 0, tzinfo=timezone.utc),
        "resolved_at": datetime(2026, 4, 10, 15, 20, 0, tzinfo=timezone.utc),
    },
    {
        "id": "INC-128",
        "service": "ArgoCD GitOps Sync Engine",
        "error": "OutOfSync & SyncFailed state across microservices",
        "symptoms": "Infrastructure changes failing to propagate from Git repository to Kubernetes cluster",
        "severity": "medium",
        "root_cause": "Custom Resource Definition (CRD) schema validation error caused by API version upgrade deprecation",
        "resolution": "Migrated CRD manifest to apiextensions.k8s.io/v1 and updated ArgoCD application manifest",
        "post_mortem": "Deprecated Kubernetes CRD API versions caused ArgoCD sync failures during cluster version upgrade.",
        "outcome": "Resolved",
        "created_at": datetime(2026, 4, 11, 10, 30, 0, tzinfo=timezone.utc),
        "resolved_at": datetime(2026, 4, 11, 11, 15, 0, tzinfo=timezone.utc),
    },

    # --- 11. Third-Party & External Dependencies ---
    {
        "id": "INC-129",
        "service": "SMS Notification Gateway",
        "error": "Twilio API 500 Server Error Outage",
        "symptoms": "SMS two-factor authentication (2FA) verification codes failing to deliver globally",
        "severity": "high",
        "root_cause": "Major upstream outage at Twilio US-East SMS routing provider",
        "resolution": "Activated automated multi-provider fallback routing to AWS SNS SMS provider",
        "post_mortem": "Single SMS provider dependency caused 2FA login blockages. Implemented automatic secondary SMS gateway fallback.",
        "outcome": "Resolved",
        "created_at": datetime(2026, 4, 12, 12, 0, 0, tzinfo=timezone.utc),
        "resolved_at": datetime(2026, 4, 12, 13, 10, 0, tzinfo=timezone.utc),
    },
    {
        "id": "INC-130",
        "service": "Payment Provider Webhook Listener",
        "error": "Stripe Signature Verification Failure",
        "symptoms": "HTTP 400 Bad Gateway on incoming payment webhooks; subscription renewals failing to process",
        "severity": "critical",
        "root_cause": "Stripe webhook secret key rotated in Stripe dashboard without updating Kubernetes Secret manifest",
        "resolution": "Updated STRIPE_WEBHOOK_SECRET environment variable in Kubernetes Secret and restarted pods",
        "post_mortem": "Manual secret rotation in payment gateway UI lacked automated Kubernetes secret sync.",
        "outcome": "Resolved",
        "created_at": datetime(2026, 4, 13, 9, 0, 0, tzinfo=timezone.utc),
        "resolved_at": datetime(2026, 4, 13, 9, 35, 0, tzinfo=timezone.utc),
    },

    # --- 12. Additional Operational Scenarios ---
    {
        "id": "INC-131",
        "service": "Email Dispatcher Service",
        "error": "SMTP TLS Certificate Handshake Timeout",
        "symptoms": "Transactional transactional emails (password reset, order receipts) queuing without sending",
        "severity": "high",
        "root_cause": "Outdated TLS 1.0 cipher suite rejected by SendGrid SMTP server after security deprecation",
        "resolution": "Upgraded Python smtplib client configuration to force TLS 1.3 protocol",
        "post_mortem": "SendGrid deprecated legacy TLS ciphers. Added automated cipher suite compliance testing to CI.",
        "outcome": "Resolved",
        "created_at": datetime(2026, 4, 14, 14, 0, 0, tzinfo=timezone.utc),
        "resolved_at": datetime(2026, 4, 14, 14, 45, 0, tzinfo=timezone.utc),
    },
    {
        "id": "INC-132",
        "service": "Feature Flag Engine",
        "error": "Uncaught JSON Null Pointer Exception in Flag Evaluator",
        "symptoms": "All feature toggles defaulting to false; new checkout UI disabled globally",
        "severity": "medium",
        "root_cause": "Malformed JSON payload uploaded to LaunchDarkly feature flag rule definition",
        "resolution": "Rolled back feature flag rule change and added JSON schema validation to flag management UI",
        "post_mortem": "Lack of client-side JSON schema validation allowed corrupt feature flag definitions to publish.",
        "outcome": "Resolved",
        "created_at": datetime(2026, 4, 15, 11, 0, 0, tzinfo=timezone.utc),
        "resolved_at": datetime(2026, 4, 15, 11, 25, 0, tzinfo=timezone.utc),
    },
    {
        "id": "INC-133",
        "service": "Data Warehouse Ingestion",
        "error": "Snowflake Auto-Suspend Warehouse Queue Delay",
        "symptoms": "ETL pipeline jobs timing out waiting for Snowflake virtual warehouse compute allocation",
        "severity": "medium",
        "root_cause": "Warehouse auto-suspend set to 60s causing frequent cold boot delays during concurrent batch queries",
        "resolution": "Increased warehouse auto-suspend setting to 10 minutes and scaled warehouse size from Small to Medium",
        "post_mortem": "Aggressive auto-suspend setting caused excessive cold start delays during peak ETL hours.",
        "outcome": "Resolved",
        "created_at": datetime(2026, 4, 16, 8, 30, 0, tzinfo=timezone.utc),
        "resolved_at": datetime(2026, 4, 16, 9, 20, 0, tzinfo=timezone.utc),
    },
    {
        "id": "INC-134",
        "service": "Session State Cache",
        "error": "Redis Client Timeout during Key Eviction",
        "symptoms": "User session authentication lookups intermittently failing with Redis::TimeoutError",
        "severity": "high",
        "root_cause": "KEYS * command executed synchronously in administrative maintenance script blocking Redis single thread",
        "resolution": "Replaced KEYS * with non-blocking SCAN command and terminated long-running admin query",
        "post_mortem": "Running KEYS * in production Redis instances blocked all incoming client queries. Banned KEYS command via Redis rename-command config.",
        "outcome": "Resolved",
        "created_at": datetime(2026, 4, 17, 10, 0, 0, tzinfo=timezone.utc),
        "resolved_at": datetime(2026, 4, 17, 10, 30, 0, tzinfo=timezone.utc),
    },
    {
        "id": "INC-135",
        "service": "Search Autocomplete Service",
        "error": "Trie Data Structure Memory Corruption",
        "symptoms": "Autocomplete API returning empty search suggestion arrays for common queries",
        "severity": "low",
        "root_cause": "Concurrent write race condition during autocomplete trie dictionary rebuild in memory",
        "resolution": "Wrapped trie update method in read-write lock mutex and forced index rebuild",
        "post_mortem": "Thread safety was missing during live dictionary updates. Added read-write mutex lock wrapper.",
        "outcome": "Resolved",
        "created_at": datetime(2026, 4, 18, 16, 15, 0, tzinfo=timezone.utc),
        "resolved_at": datetime(2026, 4, 18, 16, 50, 0, tzinfo=timezone.utc),
    },
    {
        "id": "INC-136",
        "service": "Recommendation Inference Model",
        "error": "Triton Inference Server Model Load OOM",
        "symptoms": "GPU memory allocation error; recommendations endpoint returning fallback generic items",
        "severity": "medium",
        "root_cause": "New recommendation model weights file size doubled (2GB to 4.5GB), exceeding GPU VRAM allocation",
        "resolution": "Quantized model weights to INT8 precision and reloaded model into GPU memory",
        "post_mortem": "Unquantized FP32 model weights exceeded GPU memory limit. Enforced INT8 quantization in ML model CI pipeline.",
        "outcome": "Resolved",
        "created_at": datetime(2026, 4, 19, 13, 40, 0, tzinfo=timezone.utc),
        "resolved_at": datetime(2026, 4, 19, 14, 30, 0, tzinfo=timezone.utc),
    },
    {
        "id": "INC-137",
        "service": "Audit Trail Logging Service",
        "error": "PostgreSQL Disk Full - No space left on device",
        "symptoms": "Database refusing write queries; error 'could not extend file pg_wal/00000001...'",
        "severity": "critical",
        "root_cause": "PostgreSQL WAL archiver script failed silently, accumulating 120GB of un-archived WAL files on disk",
        "resolution": "Fixed S3 WAL archive script permissions, purged archived WAL segments, and expanded EBS volume",
        "post_mortem": "WAL archiver failure went unnoticed until disk filled up. Added explicit WAL archive lag metrics and disk space alerts.",
        "outcome": "Resolved",
        "created_at": datetime(2026, 4, 20, 9, 0, 0, tzinfo=timezone.utc),
        "resolved_at": datetime(2026, 4, 20, 10, 15, 0, tzinfo=timezone.utc),
    },
    {
        "id": "INC-138",
        "service": "WebSocket Gateway Cluster",
        "error": "File Descriptor Limit Exhaustion (Too many open files)",
        "symptoms": "New client real-time WebSocket connection attempts failing with HTTP 500 error",
        "severity": "high",
        "root_cause": "Linux system ulimit soft open file descriptor cap set to default 1024 on container host",
        "resolution": "Increased sysctl fs.file-max and container ulimit open file descriptor cap to 65535",
        "post_mortem": "High-concurrency WebSocket connections hit default Linux OS open file limits. Enforced ulimit settings in host provisioning script.",
        "outcome": "Resolved",
        "created_at": datetime(2026, 4, 21, 15, 10, 0, tzinfo=timezone.utc),
        "resolved_at": datetime(2026, 4, 21, 15, 45, 0, tzinfo=timezone.utc),
    },
    {
        "id": "INC-139",
        "service": "Internal Admin Portal",
        "error": "CORS Header Misconfiguration Blocking Requests",
        "symptoms": "Access to /admin-api/users blocked by browser CORS policy: No 'Access-Control-Allow-Origin' header",
        "severity": "low",
        "root_cause": "Production domain added to CORS whitelist missing https:// scheme prefix in FastAPI middleware config",
        "resolution": "Updated CORS allow_origins list in config.py to include explicit https:// domain scheme",
        "post_mortem": "CORS domain entry lacked scheme protocol prefix. Added origin validation helper in FastAPI app init.",
        "outcome": "Resolved",
        "created_at": datetime(2026, 4, 22, 11, 20, 0, tzinfo=timezone.utc),
        "resolved_at": datetime(2026, 4, 22, 11, 40, 0, tzinfo=timezone.utc),
    },
    {
        "id": "INC-140",
        "service": "PDF Invoice Service",
        "error": "Headless Chrome Browser Crash in Puppeteer",
        "symptoms": "Invoice downloads returning HTTP 500 Internal Server Error; zombie Chrome processes accumulating",
        "severity": "medium",
        "root_cause": "Shared memory /dev/shm size set to default 64MB in Docker container causing Chrome browser crashes",
        "resolution": "Added --shm-size=2gb flag to Docker run configuration and updated Puppeteer launch args (--disable-dev-shm-usage)",
        "post_mortem": "Headless Chrome required larger shared memory buffer for rendering heavy PDF invoices.",
        "outcome": "Resolved",
        "created_at": datetime(2026, 4, 23, 14, 0, 0, tzinfo=timezone.utc),
        "resolved_at": datetime(2026, 4, 23, 14, 35, 0, tzinfo=timezone.utc),
    },
    {
        "id": "INC-141",
        "service": "Order Processing Queue",
        "error": "Poison Pill Message Infinite Loop",
        "symptoms": "Worker process CPU at 100%; order processing stopped as same corrupted order message retried endlessly",
        "severity": "high",
        "root_cause": "Corrupted JSON order payload missing required shipping_address field caused unhandled exception and continuous requeue",
        "resolution": "Configured SQS Dead Letter Queue (DLQ) with maxReceiveCount=3 and deployed JSON schema validation fix",
        "post_mortem": "Lack of Dead Letter Queue caused poison pill messages to block queue processing indefinitely.",
        "outcome": "Resolved",
        "created_at": datetime(2026, 4, 24, 8, 30, 0, tzinfo=timezone.utc),
        "resolved_at": datetime(2026, 4, 24, 9, 15, 0, tzinfo=timezone.utc),
    },
    {
        "id": "INC-142",
        "service": "Edge API Gateway",
        "error": "HTTP 502 Bad Gateway - Upstream TLS Handshake Timeout",
        "symptoms": "Intermittent 502 errors on edge proxy during high-volume customer checkout requests",
        "severity": "high",
        "root_cause": "TLS session resumption ticket cache disabled on upstream microservice Envoy proxies, forcing full TLS handshakes",
        "resolution": "Enabled TLS session tickets and connection keep-alive pooling in Envoy proxy config",
        "post_mortem": "Full TLS handshakes for every incoming request saturated CPU on Envoy sidecars during traffic spikes.",
        "outcome": "Resolved",
        "created_at": datetime(2026, 4, 25, 10, 15, 0, tzinfo=timezone.utc),
        "resolved_at": datetime(2026, 4, 25, 10, 50, 0, tzinfo=timezone.utc),
    }
]

async def aseed_incidents(db: Session) -> None:
    for data in SEED_INCIDENTS:
        existing = db.query(Incident).filter(Incident.id == data["id"]).first()
        if not existing:
            incident = Incident(
                id=data["id"],
                service=data["service"],
                error=data["error"],
                symptoms=data["symptoms"],
                severity=data["severity"],
                root_cause=data.get("root_cause"),
                resolution=data.get("resolution"),
                post_mortem=data.get("post_mortem"),
                outcome=data.get("outcome", "Resolved"),
                created_at=data["created_at"],
                resolved_at=data.get("resolved_at"),
                memory_retained=False,
            )
            db.add(incident)
            db.commit()
            db.refresh(incident)
        else:
            if data.get("post_mortem") and not existing.post_mortem:
                existing.post_mortem = data.get("post_mortem")
                db.commit()

    # Retain all eligible resolved incidents in SQLite that are pending retention
    unretained_resolved = db.query(Incident).filter(
        Incident.outcome.ilike("resolved"),
        Incident.memory_retained == False,
    ).all()

    for inc in unretained_resolved:
        if inc.root_cause or inc.resolution:
            retain_res = await hindsight_service.aretain_incident(
                incident_id=inc.id,
                service=inc.service,
                error=inc.error,
                symptoms=inc.symptoms,
                severity=inc.severity,
                root_cause=inc.root_cause,
                resolution=inc.resolution,
                post_mortem=inc.post_mortem,
                outcome=inc.outcome,
            )
            if retain_res.get("success"):
                inc.memory_retained = True
                db.commit()

def seed_incidents(db: Session) -> None:
    import asyncio
    try:
        loop = asyncio.get_running_loop()
    except RuntimeError:
        loop = None

    if loop and loop.is_running():
        loop.create_task(aseed_incidents(db))
    else:
        asyncio.run(aseed_incidents(db))
